const crypto=require('node:crypto');const {getDb}=require('../database');const {getProvider}=require('../payments');const orders=require('./orderService');
function invoice(){return `RYN-${Date.now()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;}
async function createPayment(token,userId,provider=getProvider()){
 const intent=orders.getIntent(token,userId);if(!intent||intent.status!=='pending'||!intent.variant_active||!intent.product_active)throw new Error('Intent pembayaran tidak valid.');
 const variant=getDb().prepare('SELECT * FROM product_variants WHERE id=? AND is_active=1').get(intent.variant_id);const total=variant.price*intent.quantity;if(!Number.isSafeInteger(total))throw new Error('Total tidak valid.');const reference=invoice();
 const claimed=getDb().prepare("UPDATE purchase_intents SET status='processing',unit_price=? WHERE token=? AND user_id=? AND status='pending'").run(variant.price,token,userId);if(claimed.changes!==1)throw new Error('Pembayaran sudah diproses.');
 let external;try{external=await provider.createPayment({reference,amount:total});}catch(error){getDb().prepare("UPDATE purchase_intents SET status='pending' WHERE token=? AND user_id=? AND status='processing'").run(token,userId);throw error;}
 return getDb().transaction(()=>{const orderId=getDb().prepare(`INSERT INTO orders(invoice,user_id,product_id,variant_id,product_name,variant_name,quantity,unit_price,total_price,note,payment_method,payment_status,status,provider_reference) VALUES(?,?,?,?,?,?,?,?,?,?,?,'pending','pending',?)`).run(reference,userId,intent.product_id,intent.variant_id,intent.product_name,intent.variant_name,intent.quantity,variant.price,total,intent.note,provider.name,external.reference).lastInsertRowid;getDb().prepare(`INSERT INTO payments(order_id,provider,provider_reference,amount,status,qr_string,payment_url,raw_response,expires_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(orderId,provider.name,external.reference,total,'pending',external.qrString||null,external.paymentUrl||null,JSON.stringify(external.raw||{}),external.expiresAt||null);getDb().prepare("UPDATE purchase_intents SET status='completed',order_id=? WHERE token=?").run(orderId,token);return{orderId,reference,total,...external,provider:provider.name};}).immediate();
}
function orderResult(payment,stocks,status='paid'){return{status,orderId:payment.order_id,userId:payment.user_id,invoice:payment.invoice,productName:payment.product_name,variantName:payment.variant_name,variantDescription:payment.variant_description||'',quantity:payment.quantity,unitPrice:payment.unit_price,total:payment.total_price,paymentMethod:payment.payment_method,reference:payment.provider_reference,stocks};}
function fulfillVerified(reference,verified){return getDb().transaction(()=>{const payment=getDb().prepare(`SELECT pay.*,o.user_id,o.product_id,o.variant_id,o.quantity,o.unit_price,o.total_price,o.invoice,o.product_name,o.variant_name,o.payment_method,v.description variant_description FROM payments pay JOIN orders o ON o.id=pay.order_id LEFT JOIN product_variants v ON v.id=o.variant_id WHERE pay.provider_reference=?`).get(reference);if(!payment)throw new Error('Payment tidak ditemukan.');if(payment.fulfilled_at)return{duplicate:true,...orderResult(payment,[],'paid')};if(verified.status!=='paid'){getDb().prepare('UPDATE payments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(verified.status,payment.id);getDb().prepare('UPDATE orders SET payment_status=? WHERE id=?').run(verified.status,payment.order_id);return orderResult(payment,[],verified.status);}if(Number(verified.amount)!==payment.amount||payment.amount!==payment.total_price)throw new Error('Nominal payment tidak cocok.');const stocks=getDb().prepare("SELECT id,content FROM stock_items WHERE variant_id=? AND status='available' ORDER BY id LIMIT ?").all(payment.variant_id,payment.quantity);if(stocks.length!==payment.quantity){getDb().prepare("UPDATE payments SET status='paid_stock_issue',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(payment.id);getDb().prepare("UPDATE orders SET payment_status='paid_stock_issue' WHERE id=?").run(payment.order_id);return orderResult(payment,[],'paid_stock_issue');}const sell=getDb().prepare("UPDATE stock_items SET status='sold',order_id=?,sold_at=CURRENT_TIMESTAMP WHERE id=? AND status='available'");const item=getDb().prepare('INSERT INTO order_items(order_id,stock_item_id,delivered_content) VALUES(?,?,?)');for(const stock of stocks){if(sell.run(payment.order_id,stock.id).changes!==1)throw new Error('Konflik stok.');item.run(payment.order_id,stock.id,stock.content);}getDb().prepare("UPDATE payments SET status='paid',fulfilled_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND fulfilled_at IS NULL").run(payment.id);getDb().prepare("UPDATE orders SET status='paid',payment_status='paid',paid_at=CURRENT_TIMESTAMP,fulfilled_at=CURRENT_TIMESTAMP WHERE id=?").run(payment.order_id);getDb().prepare('UPDATE products SET sold_count=sold_count+? WHERE id=?').run(payment.quantity,payment.product_id);return orderResult(payment,stocks,'paid');}).immediate();}
async function checkPayment(reference,userId){const row=getDb().prepare('SELECT pay.provider,pay.amount,o.user_id FROM payments pay JOIN orders o ON o.id=pay.order_id WHERE pay.provider_reference=?').get(reference);if(!row||(userId!=null&&row.user_id!==userId))throw new Error('Payment tidak ditemukan.');const verified=await getProvider(row.provider).checkPayment(reference,row.amount);return fulfillVerified(reference,verified);}
async function handleWebhook(providerName,payload){const verified=await getProvider(providerName).handleWebhook(payload);return fulfillVerified(verified.reference,verified);}
module.exports={createPayment,checkPayment,handleWebhook,fulfillVerified};
