const crypto=require('node:crypto');
const {getDb}=require('../database');
const {getProvider}=require('../payments');
const {config}=require('../config');
const restock=require('./restockService');

function normalizeCode(value){const code=String(value||'').trim().toUpperCase();if(!/^[A-Z0-9_-]{3,32}$/.test(code))throw new Error('Kode harus 3-32 karakter: huruf, angka, _ atau -.');return code;}
function positiveInt(value,label='Nominal'){const n=Number(String(value||'').replace(/[._\s]/g,''));if(!Number.isSafeInteger(n)||n<=0)throw new Error(`${label} harus angka positif.`);return n;}
function createGift(code,total,maxClaims,mode='fixed',adminId=null){code=normalizeCode(code);total=positiveInt(total,'Total gift');maxClaims=positiveInt(maxClaims,'Jumlah penerima');mode=String(mode||'fixed').trim().toLowerCase();if(mode==='rata')mode='fixed';if(!['fixed','random'].includes(mode))throw new Error('Mode harus fixed/rata atau random.');if(total<maxClaims)throw new Error('Total gift minimal sama dengan jumlah penerima.');getDb().prepare('INSERT INTO saldo_gifts(code,total_amount,remaining_amount,max_claims,mode,created_by) VALUES(?,?,?,?,?,?)').run(code,total,total,maxClaims,mode,adminId);return getGift(code);}
function getGift(code){return getDb().prepare('SELECT * FROM saldo_gifts WHERE code=? COLLATE NOCASE').get(String(code||'').trim());}
function listGifts(limit=30){return getDb().prepare('SELECT * FROM saldo_gifts ORDER BY created_at DESC LIMIT ?').all(limit);}
function closeGift(code){return getDb().prepare('UPDATE saldo_gifts SET is_active=0 WHERE code=? COLLATE NOCASE').run(String(code||'').trim()).changes>0;}
function claimGift(rawCode,userId){const code=normalizeCode(rawCode);return getDb().transaction(()=>{const gift=getGift(code);if(!gift||!gift.is_active)throw new Error('Gift tidak ditemukan atau sudah ditutup.');if(gift.claimed_count>=gift.max_claims||gift.remaining_amount<=0)throw new Error('Gift sudah habis.');if(getDb().prepare('SELECT 1 FROM saldo_gift_claims WHERE gift_code=? COLLATE NOCASE AND user_id=?').get(code,userId))throw new Error('Kamu sudah pernah mengambil gift ini.');const user=getDb().prepare('SELECT balance FROM users WHERE telegram_id=?').get(userId);if(!user)throw new Error('User tidak ditemukan. Buka /start terlebih dahulu.');const remainingClaims=gift.max_claims-gift.claimed_count;let amount;if(remainingClaims===1)amount=gift.remaining_amount;else if(gift.mode==='fixed')amount=Math.max(1,Math.floor(gift.remaining_amount/remainingClaims));else{const min=1,avg=Math.floor(gift.remaining_amount/remainingClaims),max=Math.max(min,Math.min(gift.remaining_amount-(remainingClaims-1),Math.max(avg,avg*2)));amount=crypto.randomInt(min,max+1);}const nextBalance=user.balance+amount;if(!Number.isSafeInteger(nextBalance))throw new Error('Saldo berada di luar rentang aman.');getDb().prepare('UPDATE users SET balance=?,updated_at=CURRENT_TIMESTAMP WHERE telegram_id=?').run(nextBalance,userId);getDb().prepare('INSERT INTO saldo_gift_claims(gift_code,user_id,amount) VALUES(?,?,?)').run(code,userId,amount);const left=gift.remaining_amount-amount,count=gift.claimed_count+1,active=count<gift.max_claims&&left>0?1:0;getDb().prepare('UPDATE saldo_gifts SET remaining_amount=?,claimed_count=?,is_active=? WHERE code=? COLLATE NOCASE').run(left,count,active,code);getDb().prepare('INSERT INTO balance_logs(user_id,amount,balance_after,note,admin_id) VALUES(?,?,?,?,NULL)').run(userId,amount,nextBalance,`Gift saldo ${code}`);return{code,amount,balance:nextBalance,remaining:left,claimed:count,maxClaims:gift.max_claims};}).immediate();}
function balanceHistory(userId,limit=15){return getDb().prepare('SELECT * FROM balance_logs WHERE user_id=? ORDER BY id DESC LIMIT ?').all(userId,limit);}
function orderForUser(ref,userId){const raw=String(ref||'').trim();return getDb().prepare(`SELECT o.*,p.name current_product_name,v.name current_variant_name,pay.status provider_status,pay.provider_reference FROM orders o LEFT JOIN products p ON p.id=o.product_id LEFT JOIN product_variants v ON v.id=o.variant_id LEFT JOIN payments pay ON pay.order_id=o.id WHERE o.user_id=? AND (o.invoice=? COLLATE NOCASE OR CAST(o.id AS TEXT)=?) LIMIT 1`).get(userId,raw,raw);}
function orderForAdmin(ref){const raw=String(ref||'').trim();return getDb().prepare(`SELECT o.*,u.username,u.first_name,pay.provider,pay.provider_reference,pay.status provider_status,pay.expires_at,pay.fulfilled_at payment_fulfilled_at FROM orders o LEFT JOIN users u ON u.telegram_id=o.user_id LEFT JOIN payments pay ON pay.order_id=o.id WHERE o.invoice=? COLLATE NOCASE OR CAST(o.id AS TEXT)=? LIMIT 1`).get(raw,raw);}
function setLowStockThreshold(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<0||n>1000)throw new Error('Batas low stock harus 0-1000.');getDb().prepare(`INSERT INTO settings(key,value) VALUES('low_stock_threshold',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).run(String(n));return n;}
function lowStockThreshold(){const row=getDb().prepare("SELECT value FROM settings WHERE key='low_stock_threshold'").get();const n=Number(row?.value);return Number.isSafeInteger(n)&&n>=0?n:3;}
function lowStockRows(){return getDb().prepare(`SELECT v.id,v.name,p.name product_name,COUNT(s.id) stock FROM product_variants v JOIN products p ON p.id=v.product_id LEFT JOIN stock_items s ON s.variant_id=v.id AND s.status='available' WHERE v.is_active=1 AND p.is_active=1 GROUP BY v.id HAVING stock<=? ORDER BY stock ASC,v.id`).all(lowStockThreshold());}
async function checkLowStock(bot){const db=getDb(),threshold=lowStockThreshold(),rows=lowStockRows(),lowIds=new Set(rows.map(r=>r.id));for(const row of db.prepare("SELECT key FROM settings WHERE key LIKE 'lowstock_last_%'").all()){const id=Number(row.key.slice('lowstock_last_'.length));if(!lowIds.has(id))db.prepare('DELETE FROM settings WHERE key=?').run(row.key);}for(const row of rows){const key=`lowstock_last_${row.id}`,last=db.prepare('SELECT value FROM settings WHERE key=?').get(key)?.value;if(String(row.stock)===String(last))continue;const text=`⚠️ LOW STOCK\n${row.product_name} — ${row.name}\nSisa stok: ${row.stock}\nBatas alert: ${threshold}`;for(const id of config.adminIds){try{await bot.telegram.sendMessage(id,text);}catch(e){console.warn('Low stock alert gagal:',e.message);}}db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,String(row.stock));}}
async function checkRestockSubscribers(bot){for(const row of restock.readyVariantSubscribers()){try{await bot.telegram.sendMessage(row.user_id,`🔔 ${row.product_name} — ${row.variant_name} sudah restok!\nStok tersedia: ${row.stock}\nGunakan /start untuk membeli.`);restock.removeVariantSubscriber(row.user_id,row.variant_id);}catch(e){console.warn('Notifikasi restok varian gagal:',e.message);}}}
function expiredDate(value){if(!value)return false;const t=Date.parse(String(value).replace(' ','T'));return Number.isFinite(t)&&t<=Date.now();}
async function expirePendingPayments(){const db=getDb();for(const row of db.prepare("SELECT pay.id,pay.provider,pay.provider_reference,pay.amount,pay.expires_at,o.id order_id FROM payments pay JOIN orders o ON o.id=pay.order_id WHERE pay.status='pending' AND pay.expires_at IS NOT NULL").all()){if(!expiredDate(row.expires_at))continue;try{const provider=getProvider(row.provider);const verified=await provider.checkPayment(row.provider_reference,row.amount);if(verified?.status==='paid')continue;if(typeof provider.cancelPayment==='function')await provider.cancelPayment(row.provider_reference,row.amount);db.transaction(()=>{db.prepare("UPDATE payments SET status='expired',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'").run(row.id);db.prepare("UPDATE orders SET status='cancelled',payment_status='expired' WHERE id=? AND status='pending'").run(row.order_id);}).immediate();}catch(e){console.warn('Auto expire payment gagal:',e.message);}}
for(const row of db.prepare("SELECT * FROM deposits WHERE status='pending' AND expires_at IS NOT NULL").all()){if(!expiredDate(row.expires_at))continue;try{const provider=getProvider(row.provider);const verified=await provider.checkPayment(row.provider_reference,row.amount);if(verified?.status==='paid')continue;if(typeof provider.cancelPayment==='function')await provider.cancelPayment(row.provider_reference,row.amount);db.prepare("UPDATE deposits SET status='expired',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'").run(row.id);}catch(e){console.warn('Auto expire deposit gagal:',e.message);}}}
function startMaintenance(bot){const run=()=>Promise.allSettled([checkLowStock(bot),checkRestockSubscribers(bot),expirePendingPayments()]);const timer=setInterval(run,5*60*1000);timer.unref?.();setTimeout(run,15000).unref?.();return timer;}
module.exports={createGift,getGift,listGifts,closeGift,claimGift,balanceHistory,orderForUser,orderForAdmin,setLowStockThreshold,lowStockThreshold,lowStockRows,checkLowStock,checkRestockSubscribers,expirePendingPayments,startMaintenance,normalizeCode};
