const productService = require('../services/productService');
const userService = require('../services/userService');
const orderService = require('../services/orderService');
const restockService = require('../services/restockService');
const { getDb } = require('../database');
const { config } = require('../config');
const { money, escapeHtml } = require('../utils/format');
const { requirePositiveInteger, requireTelegramId, requireText } = require('../utils/validation');
function parts(ctx) { return ctx.message.text.replace(/^\/\w+(?:@\w+)?\s*/, '').split('|').map(v=>v.trim()); }
function exactParts(ctx,min,max=min){const v=parts(ctx);if(v.length<min||v.length>max)throw new Error('Jumlah parameter tidak sesuai.');return v;}
function adminOnly(handler){return async ctx=>{if(!ctx.from||!config.adminIds.has(String(ctx.from.id)))return ctx.reply('⛔ Perintah khusus admin.');try{await handler(ctx);}catch(e){await ctx.reply(`❌ ${e.message}`);}};}
function registerAdminCommands(bot){
 bot.command('admin',adminOnly(ctx=>ctx.reply(`<b>Panel Admin RynAssist</b>\n\n/addproduk kode,kategori,nama,harga,deskripsi\n/addproduct KODE | Nama | Harga | Deskripsi (format lama)\n/editproduct ID | field | nilai\n/deleteproduct ID\n/addvariant PRODUCT_ID | Nama | Harga | Kode | Deskripsi\n/editvariant VARIANT_ID | field | nilai\n/deletevariant VARIANT_ID\n/variants PRODUCT_ID\n/restockvariant VARIANT_ID | item1 | item2\n/restock ID | item1 | item2\n/stocks\n/orders\n/users\n/balance USER_ID | jumlah (+/-) | catatan\n/broadcast pesan\n/stats`,{parse_mode:'HTML'})));
 bot.command('addproduk',adminOnly(async ctx=>{const raw=ctx.message.text.replace(/^\/addproduk(?:@\w+)?\s*/i,'').trim();const v=raw.split(',').map(x=>x.trim());if(v.length!==5||v.some(x=>!x))throw new Error('Gunakan: /addproduk kode,kategori,nama,harga,deskripsi\nContoh: /addproduk cc7,capcut pro,Capcut Pro 7 Hari,900,Akun premium');const r=productService.addProductVariant({code:v[0],category:v[1],name:v[2],price:v[3],description:v[4]});await ctx.reply(`✅ Produk berhasil ditambahkan.\nKategori: ${v[1]}\nVariasi: ${v[2]}\nID Produk: ${r.productId}\nID Variasi: ${r.variantId}`);}));
 bot.command('addproduct',adminOnly(async ctx=>{let v;try{v=exactParts(ctx,3,4);}catch{throw new Error('Format: /addproduct KODE | Nama | Harga | Deskripsi');}const id=productService.createProduct({code:v[0],name:v[1],price:v[2],description:v[3]||''});await ctx.reply(`✅ Produk dibuat dengan ID ${id}.`);}));
 bot.command('editproduct',adminOnly(async ctx=>{let v;try{v=exactParts(ctx,3);}catch{throw new Error('Format: /editproduct ID | field | nilai');}const id=requirePositiveInteger(v[0],'ID produk');if(!productService.updateProduct(id,v[1].toLowerCase(),v[2]).changes)throw new Error('Produk tidak ditemukan.');await ctx.reply('✅ Produk diperbarui.');}));
 bot.command('deleteproduct',adminOnly(async ctx=>{const v=exactParts(ctx,1);const r=productService.deleteProduct(requirePositiveInteger(v[0],'ID produk'));if(!r.changes)throw new Error('Produk tidak ditemukan.');await ctx.reply('✅ Produk dihapus/dinonaktifkan.');}));
 bot.command('addvariant',adminOnly(async ctx=>{let v;try{v=exactParts(ctx,3,5);}catch{throw new Error('Format: /addvariant PRODUCT_ID | Nama | Harga | Kode | Deskripsi');}const id=productService.createVariant(v[0],v[1],v[2],v[3],v[4]);await ctx.reply(`✅ Varian dibuat dengan ID ${id}.`);}));
 bot.command('editvariant',adminOnly(async ctx=>{const v=exactParts(ctx,3);const r=productService.updateVariant(v[0],v[1].toLowerCase(),v[2]);if(!r.changes)throw new Error('Varian tidak ditemukan.');await ctx.reply('✅ Varian diperbarui.');}));
 bot.command('deletevariant',adminOnly(async ctx=>{const v=exactParts(ctx,1);const r=productService.deleteVariant(v[0]);if(!r.changes)throw new Error('Varian tidak ditemukan.');await ctx.reply('✅ Varian dinonaktifkan.');}));
 bot.command('variants',adminOnly(async ctx=>{const v=exactParts(ctx,1);const p=productService.getProduct(v[0]);if(!p)throw new Error('Produk tidak ditemukan.');const rows=productService.listVariants(v[0]);const text=rows.map(x=>`${x.id}. ${escapeHtml(x.name)} — ${money(x.price)} — stok ${x.available_stock}${x.is_active?'':' — nonaktif'}`).join('\n')||'Belum ada varian.';await ctx.reply(`<b>${escapeHtml(p.name)}</b>\n\n${text}`,{parse_mode:'HTML'});}));
 bot.command('restockvariant',adminOnly(async ctx=>{const v=parts(ctx);if(v.length<2||v.length>101)throw new Error('Format: /restockvariant VARIANT_ID | item1 | item2 (maksimal 100 item)');const variant=productService.getVariant(v[0]);if(!variant)throw new Error('Varian tidak ditemukan.');const count=productService.addVariantStock(v[0],v.slice(1));await ctx.reply(`✅ ${count} item ditambahkan ke ${variant.product_name} — ${variant.name}.`);const subscribers=restockService.takeSubscribers(variant.product_id);for(const row of subscribers){try{await ctx.telegram.sendMessage(row.user_id,`🔔 ${variant.product_name} telah restok! Gunakan /start untuk membeli.`);}catch(e){console.warn(e.message);}}}));
 bot.command('restock',adminOnly(async ctx=>{const v=parts(ctx);if(v.length<2||v.length>101)throw new Error('Format: /restock ID | item1 | item2 (maksimal 100 item)');const [rawId,...items]=v,id=requirePositiveInteger(rawId,'ID produk'),p=productService.getProduct(id);if(!p)throw new Error('Produk tidak ditemukan.');const count=productService.addStock(id,items);await ctx.reply(`✅ ${count} item ditambahkan ke ${p.name}.`);}));
 bot.command('stocks',adminOnly(async ctx=>{const rows=productService.stockSummary();await ctx.reply(`<b>📦 Stok</b>\n\n${rows.map(p=>`${p.id}. ${escapeHtml(p.name)} — tersedia ${p.available_stock}, terjual ${p.sold_count}, total ${p.total_stock}`).join('\n')||'Belum ada produk.'}`,{parse_mode:'HTML'});}));
 bot.command('orders',adminOnly(async ctx=>{const rows=orderService.listOrders();await ctx.reply(`<b>🧾 Order terbaru</b>\n\n${rows.map(o=>`#${o.id} ${o.invoice} — ${escapeHtml(o.name)} — ${escapeHtml(o.variant_name)} x${o.quantity} @${money(o.unit_price)} = ${money(o.total_price)} — ${o.payment_method}/${o.payment_status||o.status}`).join('\n')||'Belum ada order.'}`,{parse_mode:'HTML'});}));
 bot.command('users',adminOnly(async ctx=>{const rows=userService.listUsers();await ctx.reply(`<b>👥 User terbaru</b>\n\n${rows.map(u=>`${u.telegram_id} @${escapeHtml(u.username||'-')} — ${money(u.balance)}`).join('\n')||'Belum ada user.'}`,{parse_mode:'HTML'});}));
 bot.command('balance',adminOnly(async ctx=>{let v;try{v=exactParts(ctx,2,3);}catch{throw new Error('Format: /balance USER_ID | jumlah (+/-) | catatan');}const id=requireTelegramId(v[0]);if(!/^[+-]?\d+$/.test(v[1]))throw new Error('Jumlah saldo harus bilangan bulat.');const amount=Number(v[1]);if(!Number.isSafeInteger(amount)||amount===0)throw new Error('Jumlah saldo tidak valid atau nol.');const balance=userService.adjustBalance(id,amount,requireText(v[2]||'Penyesuaian admin','Catatan',200),ctx.from.id);await ctx.reply(`✅ Saldo baru: ${money(balance)}.`);}));
 bot.command('broadcast',adminOnly(async ctx=>{const message=requireText(ctx.message.text.replace(/^\/broadcast(?:@\w+)?\s*/,''),'Pesan broadcast',3500),users=getDb().prepare('SELECT telegram_id FROM users').all();let sent=0;for(const u of users){try{await ctx.telegram.sendMessage(u.telegram_id,`📣 <b>Pengumuman RynAssist</b>\n\n${escapeHtml(message)}`,{parse_mode:'HTML'});sent++;}catch{}}await ctx.reply(`✅ Broadcast terkirim ke ${sent}/${users.length} user.`);}));
 bot.command('stats',adminOnly(async ctx=>{const s=getDb().prepare(`SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM products WHERE is_active=1) products,(SELECT COUNT(*) FROM orders WHERE status='paid') orders,(SELECT COALESCE(SUM(total_price),0) FROM orders WHERE status='paid') revenue,(SELECT COUNT(*) FROM stock_items WHERE status='available') stock`).get();await ctx.reply(`<b>📊 Statistik</b>\nUser: ${s.users}\nProduk aktif: ${s.products}\nOrder sukses: ${s.orders}\nOmzet: ${money(s.revenue)}\nStok tersedia: ${s.stock}`,{parse_mode:'HTML'});}));
}
module.exports={registerAdminCommands};