const productService = require('../services/productService');
const userService = require('../services/userService');
const orderService = require('../services/orderService');
const restockService = require('../services/restockService');
const voucherService=require('../services/voucherService');
const settings=require('../services/settingsService');
const backup=require('../services/backupService');
const { getDb } = require('../database');
const { config } = require('../config');
const { money, escapeHtml } = require('../utils/format');
const { requirePositiveInteger, requireTelegramId, requireText } = require('../utils/validation');
function parts(ctx) { return ctx.message.text.replace(/^\/\w+(?:@\w+)?\s*/, '').split('|').map(v=>v.trim()); }
function exactParts(ctx,min,max=min){const v=parts(ctx);if(v.length<min||v.length>max)throw new Error('Jumlah parameter tidak sesuai.');return v;}
function adminOnly(handler){return async ctx=>{if(!ctx.from||!config.adminIds.has(String(ctx.from.id)))return ctx.reply('⛔ Perintah khusus admin.');try{await handler(ctx);}catch(e){await ctx.reply(`❌ ${e.message}`);}};}
function variantByCode(code){return getDb().prepare('SELECT v.*,p.name product_name FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.code=? COLLATE NOCASE').get(String(code).trim());}
async function notifyRestock(ctx,variant){const subscribers=restockService.takeSubscribers(variant.product_id);for(const row of subscribers){try{await ctx.telegram.sendMessage(row.user_id,`🔔 ${variant.product_name} telah restok! Gunakan /start untuk membeli.`);}catch(e){console.warn(e.message);}}}
function dsProducts(){return getDb().prepare("SELECT p.id,p.name,COUNT(s.id) stock FROM products p JOIN product_variants v ON v.product_id=p.id AND v.is_active=1 JOIN stock_items s ON s.variant_id=v.id AND s.status='available' WHERE p.is_active=1 GROUP BY p.id HAVING stock>0 ORDER BY p.name COLLATE NOCASE").all();}
function dsVariants(id){return getDb().prepare("SELECT v.id,v.name,COUNT(s.id) stock FROM product_variants v JOIN stock_items s ON s.variant_id=v.id AND s.status='available' WHERE v.product_id=? AND v.is_active=1 GROUP BY v.id HAVING stock>0 ORDER BY v.name COLLATE NOCASE").all(id);}
function maskStock(v){const s=String(v||'').trim(),i=s.indexOf('|');if(i>=0)return `${s.slice(0,i)} | ••••••••`;return s.length>50?`${s.slice(0,47)}...`:s;}
async function dsShow(ctx,text,keyboard){const x={parse_mode:'HTML',reply_markup:{inline_keyboard:keyboard}};if(ctx.callbackQuery){try{return await ctx.editMessageText(text,x);}catch(e){if(String(e.message).includes('message is not modified'))return;throw e;}}return ctx.reply(text,x);}
async function dsProductMenu(ctx){const rows=dsProducts();return dsShow(ctx,'🗑️ <b>HAPUS STOK</b>\n\nPilih produk:',[...rows.map(x=>[{text:`${x.name} (${x.stock})`,callback_data:`ds:p:${x.id}`}]),[{text:'❌ Tutup',callback_data:'ds:close'}]]);}
async function dsVariantMenu(ctx,id){const p=productService.getProduct(id),rows=dsVariants(id);if(!p)throw new Error('Produk tidak ditemukan.');if(rows.length===1)return dsStockMenu(ctx,rows[0].id,0);return dsShow(ctx,`🗑️ <b>${escapeHtml(p.name)}</b>\n\nPilih variasi:`,[...rows.map(x=>[{text:`${x.name} (${x.stock})`,callback_data:`ds:v:${x.id}:0`}]),[{text:'◀️ Kembali',callback_data:'ds:products'}]]);}
async function dsStockMenu(ctx,id,page=0){const v=productService.getVariant(id);if(!v)throw new Error('Varian tidak ditemukan.');const total=getDb().prepare("SELECT COUNT(*) count FROM stock_items WHERE variant_id=? AND status='available'").get(id).count,pages=Math.max(1,Math.ceil(total/10)),pg=Math.min(Math.max(0,Number(page)||0),pages-1),rows=getDb().prepare("SELECT id,content FROM stock_items WHERE variant_id=? AND status='available' ORDER BY id ASC LIMIT 10 OFFSET ?").all(id,pg*10);const kb=rows.map((s,i)=>[{text:`Stok ${pg*10+i+1} — ${maskStock(s.content)}`,callback_data:`ds:s:${s.id}:${id}:${pg}`}]);if(pages>1){const n=[];if(pg)n.push({text:'⬅️',callback_data:`ds:v:${id}:${pg-1}`});n.push({text:`${pg+1}/${pages}`,callback_data:'ds:none'});if(pg<pages-1)n.push({text:'➡️',callback_data:`ds:v:${id}:${pg+1}`});kb.push(n);}if(total)kb.push([{text:'🗑 Hapus Semua Stok',callback_data:`ds:allask:${id}`}]);kb.push([{text:'◀️ Kembali',callback_data:`ds:p:${v.product_id}`}]);return dsShow(ctx,`📦 <b>Daftar Stok</b>\n${escapeHtml(v.product_name)} — ${escapeHtml(v.name)}\nStok tersedia: ${total}`,kb);}
function registerAdminCommands(bot){
 bot.command('admin',adminOnly(ctx=>ctx.reply(`<b>Panel Admin RynAssist</b>\n\n/addproduk kode,kategori,nama,harga,deskripsi\n/setbulk KODE | 5:3000 | 10:2000\n/hapusbulk KODE\n/setpesan KODE | pesan\n/hapuspesan KODE\n/restockvariant ID | item1 | item2\n/restockakun ID | email:password | email:password\n/restockfile VARIANT_ID — lalu upload .txt\n/delstok — pilih stok lewat tombol\n/delstokall VARIANT_ID\n/stocks\n/orders\n/users\n/balance USER_ID | +/-jumlah | catatan\n/broadcast JUDUL | isi\n/addvoucher KODE | NOMINAL | MAX_PAKAI\n/delvoucher KODE\n/vouchers\n/banner on|off\n/setbanner URL\n/setnotif CHAT_ID\n/backup\n/stats`,{parse_mode:'HTML'})));
 bot.command('setbulk',adminOnly(async ctx=>{const v=parts(ctx);if(v.length<2)throw new Error('Format: /setbulk KODE_VARIASI | 5:3000 | 10:2000');const tiers=v.slice(1).map(x=>{const m=x.match(/^(\d+)\s*:\s*(\d+)$/);if(!m)throw new Error('Tier harus format MIN:HARGA.');return{min:Number(m[1]),price:Number(m[2])};});const r=productService.setBulkTiersByCode(v[0],tiers);await ctx.reply(`✅ Bulk ${r.name} disimpan.\n${productService.parseBulkTiers(r.bulk_tiers).map(t=>`↳ Bulk: ≥${t.min} → ${money(t.price)} / pcs`).join('\n')}`);}));
 bot.command('hapusbulk',adminOnly(async ctx=>{const code=ctx.message.text.replace(/^\/hapusbulk(?:@\w+)?\s*/i,'').trim();const r=productService.clearBulkTiersByCode(code);await ctx.reply(`✅ Harga bulk ${r.name} dihapus.`);}));
 bot.command('addproduk',adminOnly(async ctx=>{const raw=ctx.message.text.replace(/^\/addproduk(?:@\w+)?\s*/i,'').trim();const v=raw.split(',').map(x=>x.trim());if(v.length!==5||v.some(x=>!x))throw new Error('Gunakan: /addproduk kode,kategori,nama,harga,deskripsi');const r=productService.addProductVariant({code:v[0],category:v[1],name:v[2],price:v[3],description:v[4]});await ctx.reply(`✅ Produk berhasil ditambahkan.\nKategori: ${v[1]}\nVariasi: ${v[2]}\nID Produk: ${r.productId}\nID Variasi: ${r.variantId}`);}));
 bot.command('setpesan',adminOnly(async ctx=>{const raw=ctx.message.text.replace(/^\/setpesan(?:@\w+)?\s*/i,'');const cut=raw.indexOf('|');if(cut<1)throw new Error('Format: /setpesan KODE | isi pesan');const code=raw.slice(0,cut).trim(),message=requireText(raw.slice(cut+1).trim(),'Pesan',3500);const v=variantByCode(code);if(!v)throw new Error('Kode variasi tidak ditemukan.');getDb().prepare('UPDATE product_variants SET post_purchase_message=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(message,v.id);await ctx.reply('✅ Pesan setelah transaksi disimpan.');}));
 bot.command('hapuspesan',adminOnly(async ctx=>{const code=ctx.message.text.replace(/^\/hapuspesan(?:@\w+)?\s*/i,'').trim(),v=variantByCode(code);if(!v)throw new Error('Kode variasi tidak ditemukan.');getDb().prepare('UPDATE product_variants SET post_purchase_message=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(v.id);await ctx.reply('✅ Pesan setelah transaksi dihapus.');}));
 bot.command('addproduct',adminOnly(async ctx=>{const v=exactParts(ctx,3,4);const id=productService.createProduct({code:v[0],name:v[1],price:v[2],description:v[3]||''});await ctx.reply(`✅ Produk dibuat dengan ID ${id}.`);}));
 bot.command('editproduct',adminOnly(async ctx=>{const v=exactParts(ctx,3),id=requirePositiveInteger(v[0],'ID produk');if(!productService.updateProduct(id,v[1].toLowerCase(),v[2]).changes)throw new Error('Produk tidak ditemukan.');await ctx.reply('✅ Produk diperbarui.');}));
 bot.command('deleteproduct',adminOnly(async ctx=>{const v=exactParts(ctx,1);if(!productService.deleteProduct(requirePositiveInteger(v[0],'ID produk')).changes)throw new Error('Produk tidak ditemukan.');await ctx.reply('✅ Produk dinonaktifkan.');}));
 bot.command('addvariant',adminOnly(async ctx=>{const v=exactParts(ctx,3,5),id=productService.createVariant(v[0],v[1],v[2],v[3],v[4]);await ctx.reply(`✅ Varian dibuat dengan ID ${id}.`);}));
 bot.command('editvariant',adminOnly(async ctx=>{const v=exactParts(ctx,3);if(!productService.updateVariant(v[0],v[1].toLowerCase(),v[2]).changes)throw new Error('Varian tidak ditemukan.');await ctx.reply('✅ Varian diperbarui.');}));
 bot.command('deletevariant',adminOnly(async ctx=>{const v=exactParts(ctx,1);if(!productService.deleteVariant(v[0]).changes)throw new Error('Varian tidak ditemukan.');await ctx.reply('✅ Varian dinonaktifkan.');}));
 bot.command('variants',adminOnly(async ctx=>{const v=exactParts(ctx,1),p=productService.getProduct(v[0]);if(!p)throw new Error('Produk tidak ditemukan.');const rows=productService.listVariants(v[0]);await ctx.reply(`<b>${escapeHtml(p.name)}</b>\n\n${rows.map(x=>`${x.id}. ${escapeHtml(x.name)} — ${money(x.price)} — stok ${x.available_stock}`).join('\n')||'Belum ada varian.'}`,{parse_mode:'HTML'});}));
 bot.command('restockvariant',adminOnly(async ctx=>{const v=parts(ctx);if(v.length<2||v.length>101)throw new Error('Format: /restockvariant VARIANT_ID | item1 | item2');const variant=productService.getVariant(v[0]);if(!variant)throw new Error('Varian tidak ditemukan.');const count=productService.addVariantStock(v[0],v.slice(1));await ctx.reply(`✅ ${count} item ditambahkan ke ${variant.product_name} — ${variant.name}.`);await notifyRestock(ctx,variant);}));
 bot.command('restockakun',adminOnly(async ctx=>{const v=parts(ctx);if(v.length<2||v.length>101)throw new Error('Format: /restockakun VARIANT_ID | email:password | email:password');const variant=productService.getVariant(v[0]);if(!variant)throw new Error('Varian tidak ditemukan.');const items=v.slice(1).map((item,index)=>{const cut=item.indexOf(':');if(cut<1)throw new Error(`Item ${index+1} harus format email:password.`);const email=requireText(item.slice(0,cut).trim(),`Email item ${index+1}`,1000);const password=requireText(item.slice(cut+1).trim(),`Password item ${index+1}`,1900);return `${email}|${password}`;});const count=productService.addVariantStock(v[0],items);await ctx.reply(`✅ ${count} akun ditambahkan ke ${variant.product_name} — ${variant.name}.`);await notifyRestock(ctx,variant);}));
 bot.command('delstok',adminOnly(async ctx=>dsProductMenu(ctx)));
 bot.action(/^ds:(.+)$/,adminOnly(async ctx=>{const a=ctx.match[1].split(':');await ctx.answerCbQuery().catch(()=>{});if(a[0]==='none')return;if(a[0]==='close')return ctx.deleteMessage().catch(()=>{});if(a[0]==='products')return dsProductMenu(ctx);if(a[0]==='p')return dsVariantMenu(ctx,requirePositiveInteger(a[1],'ID produk'));if(a[0]==='v')return dsStockMenu(ctx,requirePositiveInteger(a[1],'ID varian'),Number(a[2])||0);if(a[0]==='s'){const sid=requirePositiveInteger(a[1],'ID stok'),vid=requirePositiveInteger(a[2],'ID varian'),pg=Number(a[3])||0,row=getDb().prepare("SELECT content FROM stock_items WHERE id=? AND variant_id=? AND status='available'").get(sid,vid);if(!row)return dsStockMenu(ctx,vid,pg);return dsShow(ctx,`⚠️ <b>Konfirmasi Hapus Stok</b>\n\n${escapeHtml(maskStock(row.content))}\n\nStok ini akan dihapus permanen.`,[[{text:'🗑 Hapus',callback_data:`ds:del:${sid}:${vid}:${pg}`}],[{text:'❌ Batal',callback_data:`ds:v:${vid}:${pg}`}]]);}if(a[0]==='del'){const sid=requirePositiveInteger(a[1],'ID stok'),vid=requirePositiveInteger(a[2],'ID varian'),pg=Number(a[3])||0;if(!getDb().prepare("DELETE FROM stock_items WHERE id=? AND variant_id=? AND status='available'").run(sid,vid).changes)throw new Error('Stok sudah tidak tersedia.');return dsStockMenu(ctx,vid,pg);}if(a[0]==='allask'){const vid=requirePositiveInteger(a[1],'ID varian'),v=productService.getVariant(vid);return dsShow(ctx,`⚠️ <b>Hapus semua stok?</b>\n\n${escapeHtml(v.product_name)} — ${escapeHtml(v.name)}\nSemua stok available akan dihapus permanen.`,[[{text:'🗑 Ya, Hapus Semua',callback_data:`ds:alldel:${vid}`}],[{text:'❌ Batal',callback_data:`ds:v:${vid}:0`}]]);}if(a[0]==='alldel'){const vid=requirePositiveInteger(a[1],'ID varian');getDb().prepare("DELETE FROM stock_items WHERE variant_id=? AND status='available'").run(vid);return dsStockMenu(ctx,vid,0);}}));
 bot.command('delstokall',adminOnly(async ctx=>{const v=exactParts(ctx,1),variantId=requirePositiveInteger(v[0],'ID varian'),variant=productService.getVariant(variantId);if(!variant)throw new Error('Varian tidak ditemukan.');const deleted=getDb().prepare("DELETE FROM stock_items WHERE variant_id=? AND status='available'").run(variantId).changes;await ctx.reply(`✅ ${deleted} stok available dihapus dari ${variant.product_name} — ${variant.name}.`);}));
 bot.command('restock',adminOnly(async ctx=>{const v=parts(ctx);if(v.length<2||v.length>101)throw new Error('Format: /restock ID | item1 | item2');const [rawId,...items]=v,id=requirePositiveInteger(rawId,'ID produk'),p=productService.getProduct(id);if(!p)throw new Error('Produk tidak ditemukan.');const count=productService.addStock(id,items);await ctx.reply(`✅ ${count} item ditambahkan ke ${p.name}.`);}));
 bot.command('stocks',adminOnly(async ctx=>{const rows=productService.stockSummary();await ctx.reply(`<b>📦 Stok</b>\n\n${rows.map(p=>`${p.id}. ${escapeHtml(p.name)} — tersedia ${p.available_stock}, terjual ${p.sold_stock||p.sold_count}, total ${p.total_stock}`).join('\n')||'Belum ada produk.'}`,{parse_mode:'HTML'});}));
 bot.command('orders',adminOnly(async ctx=>{const rows=orderService.listOrders();await ctx.reply(`<b>🧾 Order terbaru</b>\n\n${rows.map(o=>`#${o.id} ${o.invoice} — ${escapeHtml(o.name)} — ${escapeHtml(o.variant_name)} x${o.quantity} = ${money(o.total_price)} — ${o.payment_method}/${o.payment_status||o.status}`).join('\n')||'Belum ada order.'}`,{parse_mode:'HTML'});}));
 bot.command('users',adminOnly(async ctx=>{const rows=userService.listUsers();await ctx.reply(`<b>👥 User terbaru</b>\n\n${rows.map(u=>`${u.telegram_id} @${escapeHtml(u.username||'-')} — ${money(u.balance)}`).join('\n')||'Belum ada user.'}`,{parse_mode:'HTML'});}));
 bot.command('balance',adminOnly(async ctx=>{const v=exactParts(ctx,2,3),id=requireTelegramId(v[0]);if(!/^[+-]?\d+$/.test(v[1]))throw new Error('Jumlah saldo harus bilangan bulat.');const amount=Number(v[1]);if(!Number.isSafeInteger(amount)||amount===0)throw new Error('Jumlah saldo tidak valid.');const balance=userService.adjustBalance(id,amount,requireText(v[2]||'Penyesuaian admin','Catatan',200),ctx.from.id);await ctx.reply(`✅ Saldo baru: ${money(balance)}.`);}));
 bot.command('broadcast',adminOnly(async ctx=>{const raw=ctx.message.text.replace(/^\/broadcast(?:@\w+)?\s*/i,'').trim(),cut=raw.indexOf('|');if(cut<1)throw new Error('Format: /broadcast JUDUL | isi pesan');const title=requireText(raw.slice(0,cut).trim(),'Judul',200),message=requireText(raw.slice(cut+1).trim(),'Pesan',3500),users=getDb().prepare('SELECT telegram_id FROM users').all();let sent=0,failed=0;for(const u of users){try{await ctx.telegram.sendMessage(u.telegram_id,`<b>${escapeHtml(title)}</b>\n\n${escapeHtml(message)}`,{parse_mode:'HTML',disable_web_page_preview:true});sent++;}catch{failed++;}}await ctx.reply(`✅ Broadcast selesai.\nBerhasil: ${sent}\nGagal: ${failed}\nTotal: ${users.length}`);}));
 bot.command('addvoucher',adminOnly(async ctx=>{const v=exactParts(ctx,2,3),r=voucherService.create(v[0],v[1],v[2]||1);await ctx.reply(`✅ Voucher <code>${escapeHtml(r.code)}</code> dibuat.\nNominal: ${money(r.amount)}\nMaks. pemakaian: ${r.max_uses}`,{parse_mode:'HTML'});}));
 bot.command('delvoucher',adminOnly(async ctx=>{const code=ctx.message.text.replace(/^\/delvoucher(?:@\w+)?\s*/i,'').trim();if(!voucherService.remove(code))throw new Error('Voucher tidak ditemukan.');await ctx.reply('✅ Voucher dinonaktifkan.');}));
 bot.command('vouchers',adminOnly(async ctx=>{const rows=voucherService.list();await ctx.reply(`<b>📮 Voucher</b>\n\n${rows.map(v=>`<code>${escapeHtml(v.code)}</code> — ${money(v.amount)} — ${v.used_count}/${v.max_uses}${v.is_active?'':' — OFF'}`).join('\n')||'Belum ada voucher.'}`,{parse_mode:'HTML'});}));
 bot.command('setbanner',adminOnly(async ctx=>{const url=ctx.message.text.replace(/^\/setbanner(?:@\w+)?\s*/i,'').trim();if(!/^https?:\/\//i.test(url))throw new Error('Format: /setbanner URL_GAMBAR');settings.setBannerUrl(url);await ctx.reply('✅ Banner disimpan dan diaktifkan.');}));
 bot.command('banner',adminOnly(async ctx=>{const mode=ctx.message.text.replace(/^\/banner(?:@\w+)?\s*/i,'').trim().toLowerCase();if(!['on','off'].includes(mode))throw new Error('Format: /banner on atau /banner off');settings.setBannerEnabled(mode==='on');await ctx.reply(`✅ Banner ${mode.toUpperCase()}.`);}));
 bot.command('setnotif',adminOnly(async ctx=>{const id=ctx.message.text.replace(/^\/setnotif(?:@\w+)?\s*/i,'').trim();if(!/^-?\d+$/.test(id))throw new Error('Format: /setnotif CHAT_ID');settings.set('notification_chat_id',id);await ctx.reply(`✅ Channel notifikasi diset ke <code>${escapeHtml(id)}</code>.`,{parse_mode:'HTML'});}));
 bot.command('backup',adminOnly(ctx=>backup.sendBackup(bot,ctx.chat.id,'Backup manual database RynAssist')));
 bot.command('stats',adminOnly(async ctx=>{const db=getDb(),s=db.prepare(`SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM products WHERE is_active=1) products,(SELECT COUNT(*) FROM orders WHERE status='paid') paid,(SELECT COALESCE(SUM(total_price),0) FROM orders WHERE status='paid') revenue,(SELECT COUNT(*) FROM stock_items WHERE status='available') available,(SELECT COUNT(*) FROM stock_items WHERE status='sold') sold`).get();await ctx.reply(`<b>📊 Statistik</b>\nUser: ${s.users}\nProduk aktif: ${s.products}\nOrder paid: ${s.paid}\nOmzet: ${money(s.revenue)}\nStok tersedia: ${s.available}\nStok terjual: ${s.sold}`,{parse_mode:'HTML'});}));
}
module.exports={registerAdminCommands};
