const {config}=require('../config');
const products=require('../services/productService');
const restock=require('../services/restockService');
const MAX_FILE_BYTES=1024*1024;
const MAX_ITEMS=5000;
function admin(ctx){return ctx.from&&config.adminIds.has(String(ctx.from.id));}
function lines(text){const rows=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!rows.length)throw new Error('File .txt kosong.');if(rows.length>MAX_ITEMS)throw new Error(`Maksimal ${MAX_ITEMS.toLocaleString('id-ID')} baris stok per file.`);return rows;}
async function notifyRestock(ctx,variant){const subscribers=restock.takeSubscribers(variant.product_id);for(const row of subscribers){try{await ctx.telegram.sendMessage(row.user_id,`🔔 ${variant.product_name} telah restok! Gunakan /start untuk membeli.`);}catch(e){console.warn('Notifikasi restok gagal:',e.message);}}}
function registerAdminFileHandlers(bot){
 bot.command('restockfile',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');const raw=ctx.message.text.replace(/^\/restockfile(?:@\w+)?\s*/i,'').trim();const id=Number(raw),variant=Number.isSafeInteger(id)&&id>0?products.getVariant(id):null;if(!variant)return ctx.reply('❌ Format: /restockfile VARIANT_ID');ctx.session.awaitingRestockFile=id;return ctx.reply(`📄 Kirim file .txt untuk ${variant.product_name} — ${variant.name}.\n\n1 baris = 1 stok. Maksimal 1 MB / ${MAX_ITEMS.toLocaleString('id-ID')} item.\nKetik /cancelrestock untuk batal.`);});
 bot.command('cancelrestock',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');if(!ctx.session.awaitingRestockFile)return ctx.reply('Tidak ada restock file yang sedang menunggu.');delete ctx.session.awaitingRestockFile;return ctx.reply('✅ Restock file dibatalkan.');});
 bot.on('document',async(ctx,next)=>{if(!ctx.session.awaitingRestockFile)return next();if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');const id=ctx.session.awaitingRestockFile,doc=ctx.message.document;if(!/\.txt$/i.test(doc.file_name||''))return ctx.reply('❌ File harus berformat .txt.');if(Number(doc.file_size||0)>MAX_FILE_BYTES)return ctx.reply('❌ File terlalu besar. Maksimal 1 MB.');const variant=products.getVariant(id);if(!variant){delete ctx.session.awaitingRestockFile;return ctx.reply('❌ Varian tidak ditemukan lagi.');}try{const link=await ctx.telegram.getFileLink(doc.file_id);const response=await fetch(link);if(!response.ok)throw new Error(`Gagal mengunduh file Telegram (${response.status}).`);const items=lines(await response.text());let total=0;for(let i=0;i<items.length;i+=100)total+=products.addVariantStock(id,items.slice(i,i+100));delete ctx.session.awaitingRestockFile;await ctx.reply(`✅ Restock dari file berhasil.\n${variant.product_name} — ${variant.name}\nStok masuk: ${total} item.`);await notifyRestock(ctx,variant);}catch(e){await ctx.reply(`❌ ${e.message}\nSilakan kirim ulang file .txt atau /cancelrestock.`);}});
}
module.exports={registerAdminFileHandlers,lines,MAX_FILE_BYTES,MAX_ITEMS};
