const { Markup }=require('telegraf');
const QRCode=require('qrcode');
const products=require('../services/productService'); const restock=require('../services/restockService'); const payment=require('../services/paymentService'); const orders=require('../services/orderService');
const {productListKeyboard,productDetailKeyboard,variantKeyboard}=require('../keyboards/product'); const {money,escapeHtml}=require('../utils/format'); const {safeEdit,safeAnswerCallback}=require('../utils/telegram'); const {isValidProductCallback}=require('../utils/callback'); const {requirePositiveInteger}=require('../utils/validation');
function listText(result,popular=false){const title=popular?'🔥 <b>PRODUK POPULER</b>':'<b>LIST PRODUCT</b>';const rows=result.items.map((p,i)=>`[${(result.page-1)*10+i+1}]. ${escapeHtml(p.name)} ( ${p.available_stock} )`);return `${title}\n\n${rows.join('\n')||'Belum ada produk aktif.'}\n\n📄 Halaman ${result.page} / ${result.pages}`;}
function currentTime(){return new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(new Date());}
function bulkLines(v){return products.parseBulkTiers(v.bulk_tiers).map(t=>`  ↳ Bulk: ≥${t.min} → ${money(t.price)} / pcs`).join('\n');}
function parentText(p,variants=[]){const rows=variants.map(v=>`• ${escapeHtml(v.name)} — ${money(v.price)} [${v.available_stock}]${bulkLines(v)?`\n${bulkLines(v)}`:''}`).join('\n');return `┌────────────────────\n│ • Produk : <b>${escapeHtml(p.name)}</b>\n│ • Stok Terjual : ${Number(p.sold_stock||p.sold_count||0)}\n│ • Desk : ${escapeHtml(p.description||'-')}\n└────────────────────\n\n┌────────────────────\n│ Varian, Harga & Stok\n${rows||'• Belum ada varian aktif.'}\n└────────────────────\n\nCurrent Date: ${currentTime()}`;}
function detailText(v,q){const unit=products.priceForQuantity(v,q);return `• Produk : <b>${escapeHtml(v.product_name)}</b>\n• Variasi : ${escapeHtml(v.name)}\n• Kode : <code>${escapeHtml(v.code||'-')}</code>\n• Sisa Produk : ${v.available_stock}\n• Desk : ${escapeHtml(v.description||'-')}\n${bulkLines(v)?`\n${bulkLines(v)}\n`:''}\n• Jumlah : ${q}\n• Harga : ${money(unit)}\n• Total Harga : ${money(unit*q)}`;}
function quantity(ctx,id){const v=ctx.session.quantities?.[id];return Number.isSafeInteger(v)&&v>0?v:1;} function setQuantity(ctx,id,v){ctx.session.quantities||={};ctx.session.quantities[id]=v;}
async function showList(ctx,page,popular=false){const result=products.listProducts(page,10,popular);await safeEdit(ctx,listText(result,popular),{parse_mode:'HTML',...productListKeyboard(result,popular)});} function replyList(ctx,page=1){const r=products.listProducts(page,10);return ctx.reply(listText(r),{parse_mode:'HTML',...productListKeyboard(r)});}
async function renderVariant(ctx,v,edit=false){let q=Math.min(quantity(ctx,v.id),v.available_stock||1);setQuantity(ctx,v.id,q);ctx.session.activeVariantId=v.id;const extra={parse_mode:'HTML',...productDetailKeyboard(ctx.from.id,v.id,q,v.available_stock)};return edit?safeEdit(ctx,detailText(v,q),extra):ctx.reply(detailText(v,q),extra);}
async function selectProduct(ctx,id,edit=false){const p=products.getProduct(id);if(!p?.is_active)return ctx.reply?.('Produk tidak aktif atau tidak ditemukan.');const variants=products.listVariants(id,true);const extra={parse_mode:'HTML',...variantKeyboard(ctx.from.id,variants)};return edit?safeEdit(ctx,parentText(p,variants),extra):ctx.reply(parentText(p,variants),extra);}
const showDetail=(ctx,id)=>selectProduct(ctx,id,true); const replyDetail=(ctx,id)=>selectProduct(ctx,id,false); async function replyDetailByPosition(ctx,pos){if(!Number.isSafeInteger(pos)||pos<=0)return ctx.reply('❌ Produk tidak tersedia. Silakan buka List Produk terbaru.');const p=products.activeProductAt(pos);return p?replyDetail(ctx,p.id):ctx.reply('❌ Produk tidak tersedia. Silakan buka List Produk terbaru.');}
function valid(ctx,action,raw,sig,label='ID varian'){const id=requirePositiveInteger(raw,label);if(!isValidProductCallback(ctx.from.id,action,id,sig))throw new Error('Callback tidak valid.');return id;}
async function sendPayment(ctx,r){const keyboard=Markup.inlineKeyboard([[Markup.button.callback('🔄 Cek Pembayaran',`paycheck:${r.reference}`)]]);const caption=`⏳ <b>Pembayaran ${escapeHtml(r.provider)}</b>\nReference: <code>${escapeHtml(r.reference)}</code>\nNominal: <b>${money(r.total)}</b>${r.expiresAt?`\nBerlaku sampai: ${escapeHtml(String(r.expiresAt))}`:''}\n\nScan QRIS di atas untuk membayar.`;if(r.qrString){const image=await QRCode.toBuffer(r.qrString,{type:'png',width:700,margin:2});return ctx.replyWithPhoto({source:image},{caption,parse_mode:'HTML',...keyboard});}if(r.paymentUrl){try{return await ctx.replyWithPhoto(r.paymentUrl,{caption,parse_mode:'HTML',...keyboard});}catch{return ctx.reply(`${caption}\n\nQRIS: ${escapeHtml(r.paymentUrl)}`,{parse_mode:'HTML',...keyboard});}}return ctx.reply(`${caption}\n\n⚠️ Data QRIS tidak diterima dari provider.`,{parse_mode:'HTML',...keyboard});}
async function sendFulfilled(ctx,r){for(const [i,s] of r.stocks.entries())await ctx.reply(`Data item ${i+1}/${r.stocks.length}:\n${s.content}`);if(r.postPurchaseMessage)await ctx.reply(r.postPurchaseMessage,{disable_web_page_preview:true});}
function registerProductHandlers(bot){bot.action(/^(products):(\d+)$/,async c=>{await c.answerCbQuery();await showList(c,Number(c.match[2]));});bot.action(/^popular:(\d+)$/,async c=>{await c.answerCbQuery();await showList(c,Number(c.match[1]),true);});
 bot.action(/^variant:(\d+):([a-f0-9]{12})$/,async c=>{const id=valid(c,'variant',c.match[1],c.match[2]);const v=products.getVariant(id,true);if(!v)return c.answerCbQuery('Varian tidak tersedia.',{show_alert:true});await c.answerCbQuery();await renderVariant(c,v,true);});
 bot.action(/^(minus|plus|reset):(\d+):([a-f0-9]{12})$/,async c=>{const [,a,r,s]=c.match,id=valid(c,a,r,s),v=products.getVariant(id,true);if(!v||c.session.activeVariantId!==id)return c.answerCbQuery('Pilihan varian tidak valid.',{show_alert:true});let q=quantity(c,id);if(a==='minus')q=Math.max(1,q-1);if(a==='plus')q=Math.min(v.available_stock||1,q+1);if(a==='reset')q=1;setQuantity(c,id,q);await c.answerCbQuery();await renderVariant(c,v,true);});bot.action('noop',c=>c.answerCbQuery());
 bot.action(/^product:(\d+):([a-f0-9]{12})$/,async c=>{const variantId=valid(c,'product',c.match[1],c.match[2]);const v=products.getVariant(variantId);await c.answerCbQuery();if(v)await selectProduct(c,v.product_id,true);});
 bot.action(/^restock:(\d+):([a-f0-9]{12})$/,async c=>{const id=valid(c,'restock',c.match[1],c.match[2]),v=products.getVariant(id,true);if(!v||v.available_stock>0)return c.answerCbQuery('Notifikasi hanya untuk varian kosong.',{show_alert:true});const active=restock.toggle(c.from.id,v.product_id);return c.answerCbQuery(active?'Notifikasi restok diaktifkan.':'Notifikasi restok dibatalkan.',{show_alert:true});});
 for(const mode of ['balance','now'])bot.action(new RegExp(`^${mode}:(\\d+):([a-f0-9]{12})$`),async c=>{const id=valid(c,mode,c.match[1],c.match[2]),v=products.getVariant(id,true),q=quantity(c,id);if(!v||c.session.activeVariantId!==id||v.available_stock<q)return c.answerCbQuery('Quantity atau stok tidak valid.',{show_alert:true});let token;try{token=orders.createIntent(c.from.id,v.product_id,q,mode==='balance'?'balance':require('../config').config.paymentProvider,id);}catch(e){return c.answerCbQuery(e.message,{show_alert:true});}await c.answerCbQuery();await c.reply('📝 Tambahkan catatan untuk penjual?',Markup.inlineKeyboard([[Markup.button.callback('📝 Isi Catatan',`note:${token}`)],[Markup.button.callback('⏭️ Skip',`skip:${token}`)],[Markup.button.callback('❌ Batal',`cancel:${token}`)]]));});
 const confirmation=async(c,token)=>{const i=orders.getIntent(token,c.from.id);if(!i)throw new Error('Intent tidak ditemukan.');const unit=products.priceForQuantity({price:i.current_price,bulk_tiers:i.bulk_tiers},i.quantity);await c.reply(`🧾 <b>Konfirmasi Pesanan</b>\n\nProduk: ${escapeHtml(i.product_name)}\nVariasi: ${escapeHtml(i.variant_name)}\nQty: ${i.quantity}\nHarga terbaru: ${money(unit)}\nTotal: ${money(unit*i.quantity)}\n\nCatatan untuk penjual:\n${escapeHtml(i.note||'(tidak ada)')}`,{parse_mode:'HTML',...Markup.inlineKeyboard([[Markup.button.callback('✅ Konfirmasi & Proses',`confirm:${token}`)],[Markup.button.callback('❌ Batal',`cancel:${token}`)]])});};
 bot.action(/^note:([a-f0-9]{24})$/,async c=>{if(!orders.getIntent(c.match[1],c.from.id))return c.answerCbQuery('Intent tidak valid.',{show_alert:true});c.session.awaitingNote=c.match[1];await c.answerCbQuery();await c.reply('Kirim catatan (maks. 500 karakter), atau /cancel.');});
 bot.on('text',async(c,next)=>{const token=c.session.awaitingNote;if(!token)return next();if(c.message.text==='/cancel'){delete c.session.awaitingNote;orders.cancelIntent(token,c.from.id);return c.reply('Pembelian dibatalkan.');}try{orders.setIntentNote(token,c.from.id,c.message.text);delete c.session.awaitingNote;await confirmation(c,token);}catch(e){await c.reply(`❌ ${e.message}`);}});
 bot.action(/^skip:([a-f0-9]{24})$/,async c=>{try{orders.setIntentNote(c.match[1],c.from.id,null);await c.answerCbQuery();await confirmation(c,c.match[1]);}catch(e){await safeAnswerCallback(c,e.message,{show_alert:true});}});
 bot.action(/^confirm:([a-f0-9]{24})$/,async c=>{const token=c.match[1],intent=orders.getIntent(token,c.from.id);if(!intent)return safeAnswerCallback(c,'Intent tidak valid.',{show_alert:true});if(intent.payment_method==='balance'){let r;try{r=orders.fulfillBalanceIntent(token,c.from.id);}catch(e){return safeAnswerCallback(c,e.message,{show_alert:true});}await c.reply(`✅ <b>Order Berhasil</b>\nInvoice: <code>${r.invoice}</code>\nProduk: ${escapeHtml(r.product.name)} — ${escapeHtml(r.variant.name)}\nTotal: ${money(r.total)}\nSisa saldo: ${money(r.balance)}`,{parse_mode:'HTML'});for(const [i,s] of r.stocks.entries())await c.reply(`Data item ${i+1}/${r.stocks.length}:\n${s.content}`);if(r.variant.post_purchase_message)await c.reply(r.variant.post_purchase_message,{disable_web_page_preview:true});return safeAnswerCallback(c,'Order berhasil!');}try{const r=await payment.createPayment(token,c.from.id);await c.answerCbQuery();await sendPayment(c,r);}catch(e){await safeAnswerCallback(c,e.message,{show_alert:true});}});
 bot.action(/^paycheck:(RYN-[A-Za-z0-9-]+)$/,async c=>{try{const r=await payment.checkPayment(c.match[1],c.from.id);await c.answerCbQuery(r.status||'Sudah diproses.',{show_alert:true});if(r.status==='paid'&&!r.duplicate)await sendFulfilled(c,r);else if(r.status==='paid_stock_issue')await c.reply('Pembayaran diterima, tetapi stok perlu ditangani admin. Kami akan menghubungi Anda.');}catch(e){await safeAnswerCallback(c,e.message,{show_alert:true});}});
 bot.action(/^cancel:([a-f0-9]{24})$/,async c=>{orders.cancelIntent(c.match[1],c.from.id);await c.answerCbQuery('Dibatalkan.');await safeEdit(c,'Pembelian dibatalkan.');});}
module.exports={registerProductHandlers,showList,replyList,showDetail,replyDetail,replyDetailByPosition,listText,detailText};
