const util=require('../services/utilityService');
const {config}=require('../config');
const {money,escapeHtml}=require('../utils/format');
function admin(ctx){return ctx.from&&config.adminIds.has(String(ctx.from.id));}
function arg(ctx,command){return ctx.message.text.replace(new RegExp(`^\\/${command}(?:@\\w+)?\\s*`,'i'),'').trim();}
function giftPrompt(ctx){ctx.session.awaitingGift=true;return ctx.reply('🎁 <b>Gift Saldo</b>\n\nKirim kode gift yang kamu punya.\nKetik /cancel untuk batal.',{parse_mode:'HTML'});}
async function claim(ctx,code){try{const r=util.claimGift(code,ctx.from.id);return ctx.reply(`🎉 <b>Gift berhasil diklaim!</b>\n\nKode: <code>${escapeHtml(r.code)}</code>\nSaldo diterima: <b>${money(r.amount)}</b>\nSaldo sekarang: <b>${money(r.balance)}</b>\nPenerima: ${r.claimed}/${r.maxClaims}`,{parse_mode:'HTML'});}catch(e){return ctx.reply(`❌ ${escapeHtml(e.message)}`,{parse_mode:'HTML'});}}
function statusLabel(row){return row.payment_status||row.provider_status||row.status||'-';}
function orderText(row,adminView=false){let text=`🧾 <b>STATUS ORDER</b>\n\nPay ID: <code>${row.id}</code>\nInvoice: <code>${escapeHtml(row.invoice)}</code>\nProduk: ${escapeHtml(row.product_name||row.current_product_name||'-')}\nVariasi: ${escapeHtml(row.variant_name||row.current_variant_name||'-')}\nJumlah: ${row.quantity}\nTotal: <b>${money(row.total_price)}</b>\nMetode: ${escapeHtml(row.payment_method||'-')}\nStatus: <b>${escapeHtml(statusLabel(row))}</b>\nDibuat: ${escapeHtml(row.created_at||'-')}\nDibayar: ${escapeHtml(row.paid_at||'-')}`;if(adminView)text+=`\n\nBuyer ID: <code>${row.user_id}</code>\nUsername: @${escapeHtml(row.username||'-')}\nProvider: ${escapeHtml(row.provider||'-')}\nProvider Ref: <code>${escapeHtml(row.provider_reference||'-')}</code>\nExpired: ${escapeHtml(row.expires_at||'-')}\nCatatan: ${escapeHtml(row.note||'-')}`;return text;}
function registerUtilityHandlers(bot){
 bot.hears('🎁 Gift Saldo',giftPrompt);bot.command('gift',async ctx=>{const code=arg(ctx,'gift');if(code)return claim(ctx,code);return giftPrompt(ctx);});
 bot.hears('💳 Riwayat Saldo',async ctx=>{const rows=util.balanceHistory(ctx.from.id);const text=rows.map(r=>`${r.amount>=0?'➕':'➖'} ${money(Math.abs(r.amount))} → ${money(r.balance_after)}\n${escapeHtml(r.note)} — ${escapeHtml(r.created_at)}`).join('\n\n')||'Belum ada riwayat saldo.';return ctx.reply(`<b>💳 RIWAYAT SALDO</b>\n\n${text}`,{parse_mode:'HTML'});});
 bot.command('riwayatsaldo',async ctx=>{const rows=util.balanceHistory(ctx.from.id);const text=rows.map(r=>`${r.amount>=0?'➕':'➖'} ${money(Math.abs(r.amount))} → ${money(r.balance_after)}\n${escapeHtml(r.note)} — ${escapeHtml(r.created_at)}`).join('\n\n')||'Belum ada riwayat saldo.';return ctx.reply(`<b>💳 RIWAYAT SALDO</b>\n\n${text}`,{parse_mode:'HTML'});});
 bot.command('cekorder',async ctx=>{const ref=arg(ctx,'cekorder');if(!ref)return ctx.reply('Format: /cekorder INVOICE');const row=util.orderForUser(ref,ctx.from.id);if(!row)return ctx.reply('❌ Order tidak ditemukan di akun kamu.');return ctx.reply(orderText(row),{parse_mode:'HTML'});});
 bot.command('addgift',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');try{const parts=arg(ctx,'addgift').split('|').map(x=>x.trim());if(parts.length<3||parts.length>4)throw new Error('Format: /addgift KODE | TOTAL | JUMLAH | fixed/random');const r=util.createGift(parts[0],parts[1],parts[2],parts[3]||'fixed',ctx.from.id);return ctx.reply(`✅ Gift dibuat.\nKode: <code>${escapeHtml(r.code)}</code>\nTotal: ${money(r.total_amount)}\nPenerima: ${r.max_claims}\nMode: ${r.mode}`,{parse_mode:'HTML'});}catch(e){return ctx.reply(`❌ ${e.message}`);}});
 bot.command('delgift',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');const code=arg(ctx,'delgift');if(!code)return ctx.reply('Format: /delgift KODE');return ctx.reply(util.closeGift(code)?'✅ Gift ditutup.':'❌ Gift tidak ditemukan.');});
 bot.command('gifts',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');const rows=util.listGifts();const text=rows.map(r=>`<code>${escapeHtml(r.code)}</code> — ${money(r.remaining_amount)}/${money(r.total_amount)} — ${r.claimed_count}/${r.max_claims} — ${r.mode}${r.is_active?'':' — OFF'}`).join('\n')||'Belum ada gift.';return ctx.reply(`<b>🎁 GIFT SALDO</b>\n\n${text}`,{parse_mode:'HTML'});});
 bot.command('orderinfo',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');const ref=arg(ctx,'orderinfo');if(!ref)return ctx.reply('Format: /orderinfo ID_ATAU_INVOICE');const row=util.orderForAdmin(ref);if(!row)return ctx.reply('❌ Order tidak ditemukan.');return ctx.reply(orderText(row,true),{parse_mode:'HTML'});});
 bot.command('lowstock',async ctx=>{if(!admin(ctx))return ctx.reply('⛔ Perintah khusus admin.');const raw=arg(ctx,'lowstock');try{if(raw){const n=util.setLowStockThreshold(raw);await util.checkLowStock(bot);return ctx.reply(`✅ Batas low stock diset ke ${n}.`);}const rows=util.lowStockRows(),threshold=util.lowStockThreshold();return ctx.reply(`<b>⚠️ LOW STOCK ≤ ${threshold}</b>\n\n${rows.map(r=>`${escapeHtml(r.product_name)} — ${escapeHtml(r.name)}: <b>${r.stock}</b>`).join('\n')||'Semua stok aman.'}`,{parse_mode:'HTML'});}catch(e){return ctx.reply(`❌ ${e.message}`);}});
 bot.on('text',async(ctx,next)=>{if(!ctx.session.awaitingGift)return next();const text=ctx.message.text.trim();if(text==='/cancel'){delete ctx.session.awaitingGift;return ctx.reply('Gift dibatalkan.');}delete ctx.session.awaitingGift;return claim(ctx,text);});
}
module.exports={registerUtilityHandlers};
